GET http://localhost/api/news/ca/en/crime HTTP/1.1

###
GET http://localhost/api/news/article/ca/en/crime HTTP/1.1

###

GET http://localhost/api/countries HTTP/1.1


###
GET http://localhost/api/country/be HTTP/1.1

###
GET http://localhost/api/country/nl/categories HTTP/1.1

###

POST http://localhost/api/country/be/ HTTP/1.1
Content-Type: application/json

{
    "category": "technology"
}

###
DELETE http://localhost/api/country/be/joselito HTTP/1.1
content-type: application/json

###
GET http://localhost/api/categories HTTP/1.1